メンバー管理に退社済み属性を追加
skeiya/ProjectsTM pull request #188
Opened 2020-09-13 01:23 UTC by MatsukageRyo

■MemberにMemberState (Working or Retirement)を追加

■EditMemberFormにMemberStateを設定するためのComboBoxを追加

■EditMeberFormはメンバ編集だけでなく、文字列編集ダイアログとして使いまわされていたので、
　文字列編集専用ダイアログとしてEditStringFormを追加。
　このEditStringFormは 本PR以前のEditMemberFormから変更ない（こちらにはMemberState設定ComboBoxはない）。

■MemberStateがWokingのメンバーしかグリッド上に表示されないよう変更

2020-09-13 12:38 UTC, skeiya requested changes

2020-09-13 12:38 UTC, skeiya commented on ProjectsTM.Model/Member.cs
> +            return Member.Parse(this.ToSerializeString(), this.State);
ToSerializeStringを変えるのが素直な気がするけど、そうするとまずいことある？

2020-09-13 12:38 UTC, skeiya commented on ProjectsTM.UI.Common/EditMemberForm.cs
> +        public EditMemberForm(string value, Member.MemberState state)
m.Clone()を引数に渡すようにしたほうがいい。

2020-09-19 09:53 UTC, MatsukageRyo commented on ProjectsTM.Model/Member.cs
> +            return Member.Parse(this.ToSerializeString(), this.State);
Parseが複数個所でコンストラクタのような使い方をされているのですが、
そこでは「メンバー名string」と「MemberState」は別変数として扱っていることが多く、
Member.Parse(dlg.Text + "/" + state.ToString());　と変更を入れていくことになりそうです。　
これだと、Parseの使い方に暗黙的なルール（+ "/" +して渡すルール）が生まれてしまうため、
別の引数として明示的に渡す((this.ToSerializeString(), this.State)と渡す）方が良いかと思いました。

2020-09-19 10:25 UTC, MatsukageRyo commented on ProjectsTM.UI.Common/EditMemberForm.cs
> +        public EditMemberForm(string value, Member.MemberState state)
ありがとうございます。修正しました。

2020-09-19 13:41 UTC, skeiya requested changes

2020-09-19 13:41 UTC, skeiya commented on ProjectsTM.Model/Member.cs
> +            return Member.Parse(this.ToSerializeString(), this.State);
ToSerializeStringがMemberクラスをシリアライズする関数です。
今回MemberクラスにStateを追加したのだから、ToSerializeStringでStateもシリアライズするように変更するのが自然な拡張です。
※私が最初になんで普通にxmlで性/名/所属を保存しとけばよかったのだけど、、、既存データの互換性のために、ひとまずToSerializeStringを変更するように対応します。

2020-09-19 14:37 UTC, skeiya commented
よくよく考えたら、MemberにStateを持つのが微妙な気がしてきました。
まず、退社状態(在社状態)はいつからいつまでという期間が伴うものであって、人と日を決めないと状態が定まらないので、単純にStateを持つのは違うと思います。
もっと言うと、特に外部スタッフの場合、一度退社してまた戻ってくるようなケースもあるので、在社期間を複数持てるようにしたくなります。

そう考えると、むしろ作業項目が似ている位置づけに思えてきました。
データ構造としては、AppDataの下にWorkingTerms(もしくはAbsentTerms)のようなレポジトリを作るのがよさそう。
編集UIもメンバーの編集とは独立させて、専用DLGを用意するイメージ。

2020-09-19 16:13 UTC, MatsukageRyo commented
@skeiya  ありがとうございます。理解しました。Memberに持たせるべきではなさそうです。
Issuesにある「不在期間の背景色をグレーにする #21」も見据えて作り直すと良さそうです。
これはクローズして、一から作ります。

2020-09-19 16:14 UTC, closed without merging