MainFormにサイズを覚えて再起動時に再現する
skeiya/ProjectsTM pull request #201
Opened 2020-09-18 15:17 UTC by naotoAkashi42

テキストファイルにサイズ情報を書き込み、
MainFormの呼び出し時に読み込むようにしました。

2020-09-18 15:57 UTC, MatsukageRyo commented
UserSettingというクラスがあるので、それを利用すると、もっとシンプルに実現できるかもしれません。

2020-09-19 14:54 UTC, skeiya requested changes

2020-09-19 14:54 UTC, skeiya commented on ProjectsTM.UI.MainForm/SizeInfoManager.cs
> +        public (int height, int width) LoadSizeInfo()
独自タプルではなく一般的なSizeを使いましょう。

2020-09-19 14:54 UTC, skeiya commented on ProjectsTM.UI.MainForm/SizeInfoManager.cs
> +    class SizeInfoManager
static classにできそう。

2020-09-19 14:54 UTC, skeiya commented on ProjectsTM.UI.MainForm/SizeInfoManager.cs
> +        public void SaveSizeInfo(int height, int width)
SizeInfoであることはクラス名から自明なので、単にSaveでよい。

2020-09-19 14:54 UTC, skeiya commented on ProjectsTM.UI.MainForm/SizeInfoManager.cs
> +        private readonly string _filePath = @".\Resource\sizeInfo.txt";
_dirPathと二重管理になっているので、Path.Combine(_dirPath, "sizeInfo.txt");としたほうが良い。

2020-09-19 14:54 UTC, skeiya commented on ProjectsTM.UI.MainForm/SizeInfoManager.cs
> +        private readonly string _dirPath = @".\Resource";
保存場所はUserSettingPathと同じフォルダを使ってください。
MainForm.csですでに定義されているので、その値を使用するようにしてください。
`Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "ProjectsTM"`

2020-09-19 14:54 UTC, skeiya commented on ProjectsTM.UI.MainForm/SizeInfoManager.cs
> +        public void CheckSourceFile()
やっていることがCheckじゃないように思います。

この関数は無くして、LoadSizeInfoのほうで既存ファイルがなかったら既定値を返すようにしたほうがシンプルになりそうです。

2020-09-19 14:54 UTC, skeiya commented on ProjectsTM.UI.MainForm/SizeInfoManager.cs
> +                while (reader.Peek() != -1)
ReadLineして戻り値のnullチェックするほうが読みやすいです。
PeekとReadLineの２関数登場するより、ReadLineだけでできるほうが簡単。

ちなみに↓本家もそうなってます。
https://docs.microsoft.com/en-us/dotnet/api/system.io.streamreader?view=netcore-3.1

2020-09-19 14:54 UTC, skeiya commented on ProjectsTM.UI.MainForm/SizeInfoManager.cs
> +            return (Convert.ToInt32(info[0]), Convert.ToInt32(info[1]));
Int32.TryParseを使って、falseの時は既定値を返すようにしましょう。

2020-09-20 02:46 UTC, naotoAkashi42 commented on ProjectsTM.UI.MainForm/SizeInfoManager.cs
> +        public (int height, int width) LoadSizeInfo()
そのように変更しました。

2020-09-20 02:48 UTC, naotoAkashi42 commented on ProjectsTM.UI.MainForm/SizeInfoManager.cs
> +    class SizeInfoManager
そのように変更しました。
わざわざMainFormにSizeInfoManager型メンバを追加する必要がない。
という意図で合っていますか？

2020-09-20 02:48 UTC, naotoAkashi42 commented on ProjectsTM.UI.MainForm/SizeInfoManager.cs
> +        public void SaveSizeInfo(int height, int width)
メソッド名はSave, Loadとしました。

2020-09-20 02:49 UTC, naotoAkashi42 commented on ProjectsTM.UI.MainForm/SizeInfoManager.cs
> +        private readonly string _filePath = @".\Resource\sizeInfo.txt";
UserSettingPathを使うようにしたので削除しました。

2020-09-20 02:49 UTC, naotoAkashi42 commented on ProjectsTM.UI.MainForm/SizeInfoManager.cs
> +        private readonly string _dirPath = @".\Resource";
UserSettingPathを渡して、XMLファイルにMainFormのサイズ情報を書き込むようにしました。

2020-09-20 02:50 UTC, naotoAkashi42 commented on ProjectsTM.UI.MainForm/SizeInfoManager.cs
> +        public void CheckSourceFile()
指摘いただいて、Loadメソッドの役割として、エラー処理するほうがシンプルであると思いました。
そのように修正しました。

2020-09-20 02:58 UTC, naotoAkashi42 commented on ProjectsTM.UI.MainForm/SizeInfoManager.cs
> +                while (reader.Peek() != -1)
ありがとうございます。
参考にします！

2020-09-20 02:58 UTC, naotoAkashi42 commented on ProjectsTM.UI.MainForm/SizeInfoManager.cs
> +            return (Convert.ToInt32(info[0]), Convert.ToInt32(info[1]));
そのように修正しました。

2020-09-20 03:00 UTC, naotoAkashi42 commented
Githubをちゃんと使ったことがなく、調べながらやっているので何か問題、ルール等に触れていたら教えてください。
よろしくお願いいたします。

2020-09-20 03:43 UTC, skeiya requested changes

2020-09-20 03:43 UTC, skeiya commented on ProjectsTM.UI.MainForm/ProjectsTM.UI.MainForm.csproj
> +    <Reference Include="System.ValueTuple, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51, processorArchitecture=MSIL">
ValueTupleの追加は不要になったはず。

2020-09-20 03:43 UTC, skeiya commented on ProjectsTM.UI.MainForm/SizeInfoManager.cs
> +        private readonly string _dirPath = @".\Resource";
同じXMLファイルを使うのであれば、UserSettingを変更してもらったほうが良いです。
あちこちから同じXMLを編集すると、どんなタグが使用済みなのかとか、干渉がわかりづらくなるので。

2020-09-20 23:17 UTC, naotoAkashi42 commented on ProjectsTM.UI.MainForm/ProjectsTM.UI.MainForm.csproj
> +    <Reference Include="System.ValueTuple, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51, processorArchitecture=MSIL">
削除しました。

2020-09-21 01:17 UTC, skeiya approved these changes
ProjectsTMのフォルダ名が２重管理になっていたところを修正しました。

2020-09-21 01:17 UTC, skeiya commented on ProjectsTM.UI.MainForm/packages.config
> +﻿<?xml version="1.0" encoding="utf-8"?>
この変更も不要なはず。

2020-09-21 01:29 UTC, merged