TaskListFormもサイズを覚えて再起動時に再現するようにする
skeiya/ProjectsTM pull request #207
Opened 2020-09-22 01:20 UTC by naotoAkashi42

SizeFormManagerをFormSizeManagerとrenameし、UI層からProjectTM.Serviceのnamespace後はに移動。あとは引数でどのformのサイズをsave,loadするのか指定できるようにしました。

2020-09-22 14:28 UTC, skeiya requested changes

2020-09-22 14:28 UTC, skeiya commented on ProjectsTM.Service/FormSizeManager.cs
> +    public static class FormSizeManager
Serviceのネームスペースに入れるのであれば、FormSizeRestoreServiceのような名前のほうが良いです。

2020-09-22 14:28 UTC, skeiya commented on ProjectsTM.Service/FormSizeManager.cs
>              if (!File.Exists(sizeInfoPath))
Save相当の実装が重複している。下で実装済みのSaveをここでも呼び出すほうが良い。

2020-09-22 14:28 UTC, skeiya commented on ProjectsTM.UI.MainForm/MainForm.cs
> +        private static string SizeInfoPath => Path.Combine(AppConfigDir, "FormSizeInfo.xml");
"FormSizeInfo.xml"というのはFormSizeManagerだけが知っていればよい情報なので、FormSizeManagerのなかでprivateに持つようにするほうが良い。
※"UserSetting.xml"も同様にUserSettingUIServiceの中に閉じ込めたほうが良いですね。

2020-09-24 23:00 UTC, MatsukageRyo requested changes

2020-09-27 00:46 UTC, MatsukageRyo requested changes

2020-09-27 00:46 UTC, MatsukageRyo commented on ProjectsTM.ViewModel/UserSetting.cs
> -        public FormSize FormSize { set; get; } = new FormSize();
・ここの削除に伴ってFormSizeの定義自体が不要にならないでしょうか？
・TaskListFormの内部変数_formSizeが不要にならないでしょうか？
・TaskListFormのコンストラクタ引数formSizeが不要にならないでしょうか？

2020-09-27 11:23 UTC, skeiya requested changes

2020-09-27 11:23 UTC, skeiya commented on ProjectsTM.Service/FormSizeRestoreService.cs
> +            if (!File.Exists(SizeInfoPath))
前回データがないときは単純にデフォルトを返せばよいと思います。
`
return new Size(DEFAULT_WIDTH, DEFAULT_HEIGHT);`

2020-09-28 12:41 UTC, naotoAkashi42 commented on ProjectsTM.ViewModel/UserSetting.cs
> -        public FormSize FormSize { set; get; } = new FormSize();
＞ここの削除に伴ってFormSizeの定義自体が不要にならないでしょうか？
＞TaskListFormの内部変数_formSizeが不要にならないでしょうか？
＞TaskListFormのコンストラクタ引数formSizeが不要にならないでしょうか？
ほかのFormSizeのメンバを使用している箇所があるので一括に削除はできなそうです。
ですが、ご指摘の通り、無駄なコードは残りそうだったのでFormSizeの中の無駄な
メンバのみ削除しました。

2020-09-28 12:43 UTC, naotoAkashi42 commented on ProjectsTM.Service/FormSizeRestoreService.cs
> +            if (!File.Exists(SizeInfoPath))
ありがとうございます！
最初FormSizeRestoreServiceが呼ばれたときにファイル自体が存在しなかった場合、
ずっとデフォルト値が返ることになると思ったのでSaveの時に存在チェックを入れるようにしました。

2020-09-28 13:35 UTC, MatsukageRyo approved these changes

2020-09-28 13:38 UTC, skeiya requested changes

2020-09-28 13:38 UTC, skeiya commented on ProjectsTM.Service/FormSizeRestoreService.cs
> +        public static Size Load( string form)
この１つの関数内で↓同じこのコードが３回出てきています。
やりたいこととしては、正常にロードできなかったらデフォルトにする、というだけのことなので自然にそのやりたいことをコードに落として冗長さを改善してみてください。
`return new Size(DEFAULT_WIDTH, DEFAULT_HEIGHT);`

2020-09-28 14:02 UTC, skeiya requested changes

2020-09-28 14:02 UTC, skeiya commented on ProjectsTM.Service/FormSizeRestoreService.cs
> +                CreateDefaultFile();
この処理必要ですか？

2020-09-30 15:01 UTC, skeiya requested changes

2020-10-04 12:44 UTC, skeiya requested changes

2020-10-04 12:44 UTC, skeiya commented on ProjectsTM.Service/FormSizeRestoreService.cs
> +                string heightStr;
前方宣言する必要はないと思います。↓こうしたほうが簡潔になります。
`var heightStr = sizeInfo.Element("height").Value;`

2020-10-04 12:44 UTC, skeiya commented on ProjectsTM.Service/FormSizeRestoreService.cs
> +                var sizeInfo = xml.Elements(form).Select(v => v).Single();
Select(v => v)ってやる意味あります？

2020-10-04 22:36 UTC, skeiya approved these changes

2020-10-04 22:37 UTC, merged