メンバーの編集画面で、全メンバー数や各所属ごとの人数を表示するように対応しました。
skeiya/ProjectsTM pull request #211
Opened 2020-10-03 07:00 UTC by naotoAkashi42

■ DLG内に合計人数や各所属人数を表示するためのlavelを追加
■ ProjectTM.Serviceに合計人数や各所属人数を数えて文字列で渡すクラスCountMemberNumServiceを追加
■ 表示、編集、追加のタイミングで表示文字列が変更されるようにManageMemberFormを変更

◆追加ボタンにアンカーがついていないバグがあったのでついでに修正。

@松蔭さん
退社済み属性の対応はまだマージされていないのでしょうか？
#22がClose?されていた、Memberクラスにそのようなプロパティがなかったこと
からそのように思ってます。

2020-10-03 08:34 UTC, MatsukageRyo commented on ProjectsTM.Service/CountMemberNumService.cs
> +        public  static string GetCountStr(AppData appData )
・AppDataは渡し過ぎのようにみえました。AppData.Membersだけでも良いかなと思いました。
・処理が長いので、関数に切り出して、処理内容が分かる関数名をつけると読みやすくなるように思いました。

2020-10-04 01:25 UTC, MatsukageRyo commented on ProjectsTM.Service/CountMemberNumService.cs
> +        public  static string GetCountStr(AppData appData )
退社属性の対応は、マージされてません。作り直しています。

2020-10-04 09:01 UTC, naotoAkashi42 commented on ProjectsTM.Service/CountMemberNumService.cs
> +        public  static string GetCountStr(AppData appData )
＞退社属性の対応は、マージされてません。作り直しています。
ありがとうございます。全人数に退社済み属性の場合という対応は保留しようと思います。

2020-10-04 12:38 UTC, skeiya requested changes

2020-10-04 12:38 UTC, skeiya commented on ProjectsTM.Service/CountMemberNumService.cs
> +        private static IEnumerable<string> GetCompanyList(Members members)
こんな感じに書くと簡潔になります。
`
members.Select(m => m.Comapy).Distinct();
`

2020-10-04 12:38 UTC, skeiya commented on ProjectsTM.Service/CountMemberNumService.cs
> +            var companyList = GetCompanyList(members);
Listであることに特別な意味はないと思うので、単にcompaniseとしたほうが良いです。
変数で受けずに↓こうしてもいいと思います。
```

foreach (var company in GetCompanies(memebers)){
 ...
}

```

2020-10-04 12:38 UTC, skeiya commented on ProjectsTM.Service/CountMemberNumService.cs
> +            var countList = GetCountList(members, companyList).ToList();
".ToList()"は不要。インデックスアクセスはElementAtでできるはず。

2020-10-04 12:38 UTC, skeiya commented on ProjectsTM.Service/CountMemberNumService.cs
> +        public  static string GetCountStr(Members members)
会社数が大きいときを考えると、この外部仕様だとどうなるだろう。
仮に、今の仕様だとして、↓こんな感じで書くと何をしているのかが読み取りやすくなります。
```
            var result = new StringBuilder("Total:" + members.Count.ToString() + " (");
            foreach(var company in GetCompanise(members))
            {
                var count = members.Count(m => m.Company.Equals(company));
                result.Append(company.Name + ":" + count.ToString() + " ");
            }
            return result.ToString() + ")";
```

2020-10-04 12:38 UTC, skeiya commented on ProjectsTM.Service/CountMemberNumService.cs
> +                count = 0;
こんな感じで簡潔に書けます。
`
count = members.Count(m => m.Company.Equals(company);`

2020-10-04 22:54 UTC, MatsukageRyo approved these changes

2020-10-06 14:52 UTC, skeiya approved these changes
コード自体はOKと思います。
仕様として、各社の人数を一覧で見れるようにしたいです。
今の動作だと、いちいち各社の人を選択しないと、その会社の人数が見れないので。

2020-10-06 14:53 UTC, merged