退社済属性の追加
skeiya/ProjectsTM pull request #216
Opened 2020-10-10 09:29 UTC by MatsukageRyo

2020-10-11 02:28 UTC, skeiya commented on ProjectsTM.Model/AbsentState.cs
> +    public enum AbsentState
外部スタッフなど、一度退社して戻ってくるケースがあるので、AbsenceとRetiredはそこまで明確に分けずらいかも。
なぜこの２つを区別したいのだっけ？

2020-10-11 11:00 UTC, MatsukageRyo commented on ProjectsTM.Model/AbsentState.cs
> +    public enum AbsentState
一時的不在なのか、退社してしまっているのか表現したくなるかと思いました。
退社して戻ってくるケースがあるのですね。

状態はAbsenceだけにして、不在期間だけ設定するよう修正します。
AbsenceStateの使い道を思いつかなければこれも後日削除します。

2020-10-11 12:59 UTC, MatsukageRyo commented on ProjectsTM.Model/AbsentState.cs
> +    public enum AbsentState
・AbsenceState周りを一旦マスクしました。
・フィルタ期間において、全て不在の場合は、表示対象メンバから除外されるよう追加しました。

2020-10-12 11:58 UTC, naotoAkashi42 approved these changes

2020-10-12 13:48 UTC, skeiya commented
ManageAbsentInfoFormのリストエリアをダブルクリックすると落ちました。

2020-10-16 14:54 UTC, skeiya requested changes
ManageAbsentInfoFormのリストエリアをダブルクリックすると落ちました。

2020-10-18 00:07 UTC, MatsukageRyo commented
@skeiya ありがとうございます。修正しました。

2020-10-18 01:46 UTC, MatsukageRyo commented
@skeiya @naotoAkashi42 
不在期間の開始日・終了日どちらか片方を空白にすると、
空白にした方を ”無期限”として扱う処理を追加しました。

2020-10-18 02:35 UTC, skeiya approved these changes

2020-10-18 02:37 UTC, skeiya approved these changes

2020-10-18 02:37 UTC, merged