キー操作改善
skeiya/ProjectsTM pull request #248
Opened 2020-10-24 06:29 UTC by super-string

・Ctrl+上下キーで一日ずらす対応
・Ctrl＋ドラッグ操作の判定修正(現状、Ctrl押してから左クリックだと動作しない。左クリックでWorkItemを選択してからCtrlキーを追加で押下するとコピーが動作する)

2020-10-24 09:17 UTC, skeiya requested changes

2020-10-24 09:17 UTC, skeiya commented on ProjectsTM.Service/WorkItemEditService.cs
> +            after.Period = after.Period.ApplyOffset(shift, _viewData.Original.Callender);
カレンダーの端々を越えようとする操作が気になります。
PeriodのIsValidのチェックを追加した方がいいかも。

2020-10-24 13:18 UTC, super-string commented on ProjectsTM.Service/WorkItemEditService.cs
> +            after.Period = after.Period.ApplyOffset(shift, _viewData.Original.Callender);
ApplyOffsetの結果Calender範囲外となったとき、Period自体がnullとなるので、IsValidではなくnullcチェックを追加しました。

2020-10-24 15:03 UTC, skeiya requested changes
masterからのマージのせいかもしれないのだけど、ドラッグ中に後からCtrlキーを押したときにコピーされなくなっています。

2020-10-25 10:48 UTC, super-string commented
> masterからのマージのせいかもしれないのだけど、ドラッグ中に後からCtrlキーを押したときにコピーされなくなっています。

対応しました。

2020-10-25 12:22 UTC, skeiya approved these changes

2020-10-25 12:22 UTC, merged