総工数のトレンドグラフを表示するUI追加
skeiya/ProjectsTM pull request #259
Opened 2020-10-30 22:43 UTC by MatsukageRyo

・管理メニューへ　「総工数トレンド」を追加
・プロジェクトごとに総工数のトレンドグラフを表示するフォーム追加

仕様も含め何かあればください。

2020-11-01 02:14 UTC, skeiya requested changes
もともとイメージしていたのは、gitのlogを使って、時系列遷移を描画するような感じでした。
※プロジェクト全体の工数が当初からどのように変化するかの差分を見れるようになる目的。

このプルリクの機能では、使用済み工数の推移を見れるようになりそうですね。それはそれでよいのかも。

2020-11-01 02:14 UTC, skeiya commented on ProjectsTM.UI.MainForm/TrendChart.cs
> +        private DateTime ParseDateTime(CallenderDay callenderDay)
Parseだと文字列データからの変換というニュアンスになるので、単にCallender2DataTimeとかのほうが良いです。
CallenderDayクラスにToDateTimeというメソッドを追加するというのでもよいと思います。

2020-11-01 07:32 UTC, MatsukageRyo commented
> もともとイメージしていたのは、gitのlogを使って、時系列遷移を描画するような感じでした。
> ※プロジェクト全体の工数が当初からどのように変化するかの差分を見れるようになる目的。
> 
> このプルリクの機能では、使用済み工数の推移を見れるようになりそうですね。それはそれでよいのかも。

@skeiya 
そういう目的だったのですね。理解しました。
git logで時系列遷移見る機能は別PRで対応します。

2020-11-01 07:43 UTC, MatsukageRyo commented on ProjectsTM.UI.MainForm/TrendChart.cs
> +        private DateTime ParseDateTime(CallenderDay callenderDay)
ありがとうございます。修正しました。

2020-11-02 10:39 UTC, skeiya approved these changes

2020-11-02 10:39 UTC, merged