過去ある時点の総工数をGitのログからを計算して、過去の総工数推移を表示
skeiya/ProjectsTM pull request #265
Opened 2020-11-03 01:03 UTC by MatsukageRyo

・Gitリポジトリから過去のAppDataを取得する処理を追加
・過去1年間1か月ごとのAppDataの総工数を計算し、トレンドを表示する処理を追加

※計算に少し時間がかかります。プログレスバーなどは後日実装予定

2020-11-14 15:41 UTC, MatsukageRyo commented
・総工数トレンドの集計対象にフィルタが適用できるよう対応
・プログレスバーの表示
を追加しました。

2020-11-15 14:46 UTC, skeiya requested changes

2020-11-15 14:46 UTC, skeiya commented on ProjectsTM.Service/GitRepositoryService.cs
> +            return SaveFile(text, oldFilePath);
実ファイルを作ってしまうと、痕跡が残り続けて何かのはずみで悪さをしないかとか、気にし続けるコストが発生してしまう。
LoadFromStreamでStreamからAppDataは作れるので、ONメモリで済ませたほうが良い。

2020-11-21 06:54 UTC, MatsukageRyo commented on ProjectsTM.Service/GitRepositoryService.cs
> +            return SaveFile(text, oldFilePath);
修正しました。
色々なところで、「ファイルの中身が入っている文字列」を「FileContent」と呼んでしまっていますが、
他に良い呼び方あれば指摘ください。

2020-11-28 02:45 UTC, skeiya commented on ProjectsTM.Service/AppDataSerializeService.cs
> +        public static AppData LoadFromStream(string text, bool isOld)
この変更は何のため？

2020-11-28 04:39 UTC, MatsukageRyo commented on ProjectsTM.Service/AppDataSerializeService.cs
> +        public static AppData LoadFromStream(string text, bool isOld)
AppDataSerializeService::LoadFromStream( )へ
「ファイルパスからの読み出し結果」も、「GitCommandRaw( )の結果」も渡せるようにする目的ですが
どちらもstringへ変換するのは簡単であったため、stringで渡せるよう変更しました。

2020-12-30 00:44 UTC, MatsukageRyo commented on ProjectsTM.Service/AppDataSerializeService.cs
> +        public static AppData LoadFromStream(string text, bool isOld)
@skeiya 
ここの変更を戻して、StreamReaderへ変換してから渡すよう修正しました。

2020-12-30 16:04 UTC, skeiya requested changes

2020-12-30 16:04 UTC, skeiya commented on ProjectsTM.Service/AppDataSerializeService.cs
> +        public static AppData DeserializeFileContent(string xml)
この処理の内容はAppDataのシリアライズとは直接関係がないので、StreamFactoryのメソッドとしてCreateFromStringのようにしたほうが良い。

2020-12-31 10:08 UTC, MatsukageRyo commented on ProjectsTM.Service/AppDataSerializeService.cs
> +        public static AppData DeserializeFileContent(string xml)
ありがとうございます。修正しました。

2020-12-31 15:55 UTC, skeiya approved these changes

2020-12-31 15:55 UTC, merged