タスクリストでMSをダブルクリックから編集可能にする対応
skeiya/ProjectsTM pull request #270
Opened 2020-11-14 14:29 UTC by naotoAkashi42

■ TaskListGridでMSの行をダブルクリックするとEditMileStoneFormを呼ぶように変更。
    クリックしたMSを特定するロジックは同じプロジェクト内で同じ名前のMSはない。
　このロジックで対象のMSを取得する。TaskListGridの253行目。

■ EditMileStoneFormで編集後元データ(viewData.Original)を編集後のMSと置換。
　
■ Grid内のデータも書き直す。

2020-11-14 15:18 UTC, MatsukageRyo commented on ProjectsTM.UI.TaskList/TaskListGrid.cs
> +                var selectMs = _viewData.Original.MileStones.Where(x => x.Name.Equals(item.WorkItem.Name) && x.Project.Equals(item.WorkItem.Project)).First();
ここは、MileStone.Dayなども照合したほうが良いのかなと思いました。

var selectMs = _viewData.Original.MileStones.Where(x => item.Equals(x)).First();
とかにしてTaskListItemクラスに
        public bool Equals(MileStone ms)
        {
            if (!IsMilestone) return false;
            if (WorkItem.Name != ms.Name) return false;
            if (WorkItem.Period.From != ms.Day) return false;
            if (WorkItem.Period.To != ms.Day) return false;
            ・
            ・
            ・
            return true;
        }

などを追加することになるのかなと思いました。

2020-11-14 15:34 UTC, MatsukageRyo commented on ProjectsTM.UI.TaskList/TaskListGrid.cs
> +                    _viewData.UpdateCallender(newWi);
これは必要そうでしょうか？

2020-11-15 02:19 UTC, naotoAkashi42 commented on ProjectsTM.UI.TaskList/TaskListGrid.cs
> +                    _viewData.UpdateCallender(newWi);
松蔭さん
ありがとうございます！

必要ありませんでした。

VeiwDataが開始日/終了日として選んでいる日付の情報を持っていてもし編集でそこに
ない日付を選んだら追加する。という処理のように勘違いしていたのですがそうでもなかったです。

ただ、だとするとタスクの編集ではUpdateCallenderAndMemberのような関数呼んでいるのですがこれは
どのような処理なのでしょうか？

2020-11-15 15:03 UTC, skeiya requested changes

2020-11-15 15:03 UTC, skeiya commented on ProjectsTM.UI.TaskList/TaskListGrid.cs
> +                var selectMs = _viewData.Original.MileStones.Where(x => x.Name.Equals(item.WorkItem.Name) && x.Project.Equals(item.WorkItem.Project)).First();
MilestoneからTaskListItemを作るときに、あとから元のMilestoneを逆引きできるように、元のMilestoneを持たせてしまうのがシンプルでよいかも。

WorkItemからMilestoneを逆引きするのは無理がありそう。いじわるパターンで、全く同じ内容のマイルストーンが複数ある場合も考えられるので。

2020-11-28 01:55 UTC, naotoAkashi42 commented
下村さん、松蔭さん
自分のローカル環境ではビルドが通るのですが
コミットするとBuild＆UnitTestに失敗するのですがこれはどういった対応をしたらよいのでしょうか？

私が修正している間にmasterに入った変更の影響で何かまずいことがあるのかと思い、
masterをマージしてみたのですがそれでも失敗してしまいます。

Details見てみると
SetUp　Nuget.exeで失敗していました。

2020-11-28 02:24 UTC, skeiya commented
githubのバージョンアップで、互換性がなくなる変更があった模様
それに追従していないactionを使い続けているたまに、エラーになっているようです
私の方で対応します

2020-11-28 02:38 UTC, naotoAkashi42 commented
ありがとうございます。

2020-11-28 02:40 UTC, skeiya approved these changes

2020-11-28 02:41 UTC, merged