タスクリストの右クリックメニュー対応
skeiya/ProjectsTM pull request #272
Opened 2020-12-05 09:04 UTC by naotoAkashi42

■　TaskListContextMenuHandlerを追加。
・　状態をDoneに変える。
・　状態変えたら再描画。

■　TaskListFormにメンバTaskListContextMenuHandlerを追加。

私は、あとはこの系から削除できてもいいかなぁくらいに思っています。
ほかに何かしたいことありますでしょうか？

2020-12-05 14:58 UTC, skeiya requested changes

2020-12-05 14:58 UTC, skeiya commented on ProjectsTM.UI.TaskList/TaskListContextMenuHandler.cs
> +            _taskListGrid.UpdateView();
このコードが無いとダメでした？
ここで明示的に描画更新しなくても、モデルデータ側で変更を検出して、イベント発報されて描画更新されるはずだと思う。

2020-12-05 14:58 UTC, skeiya commented on ProjectsTM.UI.TaskList/TaskListContextMenuHandler.cs
> +        private TaskListGrid _taskListGrid;
クラス間の相互参照になっている。
多分EditServiceだけあれば足りるはず。

2020-12-06 04:26 UTC, naotoAkashi42 commented on ProjectsTM.UI.TaskList/TaskListContextMenuHandler.cs
> +            _taskListGrid.UpdateView();
＞このコードが無いとダメでした？
右クリックからDONEに変更して、
呼び出し履歴見ると    
TaskGrid側のイベントで    
private void _undoService_Changed(object sender, IEditedEventArgs e)
        {

            UpdateView();
            this.Invalidate();
        }

が呼ばれているので
更新されそうなものですが、

なぜか
明示的にTaskListContextMenuHandler側で
_taskListGrid.UpdateView()；しないとタイミングが遅れて描画更新が走ります。
（右クリックー＞Doneにして、べつのTaskListItemをDoneにするー＞
一回前のTaskListItemの描画が更新されます。）

2020-12-07 22:48 UTC, skeiya commented on ProjectsTM.UI.TaskList/TaskListContextMenuHandler.cs
> +            _taskListGrid.UpdateView();
そっか。ちょっと調べて見ますね。

2020-12-08 13:07 UTC, skeiya requested changes

2020-12-08 13:07 UTC, skeiya commented on ProjectsTM.UI.TaskList/TaskListContextMenuHandler.cs
> +            _taskListGrid.UpdateView();
更新通知のタイミングに問題があったので修正しました。
this.Invalidate();を明示的に呼ぶ必要はなくなったはずです。

2020-12-11 22:07 UTC, naotoAkashi42 commented
対応ありがとうございます。
明示的に再描画しなくても大丈夫なことが確認できました。

2020-12-11 22:35 UTC, naotoAkashi42 commented on ProjectsTM.UI.TaskList/TaskListContextMenuHandler.cs
> +        private TaskListGrid _taskListGrid;
すみません。

↓のような関係になっているように見えていて
・何がまずいことになっているのか？
・修正イメージ
がわかっていません。

TaskListGrid ←TaskListForm 
　　　　　　　　　↓
               ↘TaskListContextHandler

  (矢印は依存関係)

TaskListGridで出す右クリックメニューを作るならTaskListGridごと渡すしかないのかなと
思ってしまっています。

よろしくお願いいたします。

2020-12-12 01:59 UTC, skeiya commented on ProjectsTM.UI.TaskList/TaskListContextMenuHandler.cs
> +        private TaskListGrid _taskListGrid;
ごめんなさい。勘違いでした。

2020-12-12 02:00 UTC, skeiya approved these changes

2020-12-12 02:00 UTC, merged