taskListのエラーソートを逆にする対応
skeiya/ProjectsTM pull request #275
Opened 2020-12-12 05:27 UTC by naotoAkashi42

■ ColDefinition.Sortを変更
ソート列がエラーの時だけ逆向きでソートするようにした。

2020-12-12 05:33 UTC, naotoAkashi42 commented
外部仕様から
エラーの行だけ今と逆向きにソートすればよいと考えて修正入れてしまったのですが、
確認で流れてきているデータを確認すると

ColDefinition.Sort内の下の処理で
listItems = listItems.OrderByDescending(l => GetText(l, sortCol, viewData)).ToList();
GetTextでもどってくる値(文字列)でソートしてるように思っていて確認すると常に"未完”が
返っているように見えたのですがこれはどういったデータ構造というかソートのロジックに
なっているのでしょうか？

2020-12-13 06:09 UTC, skeiya requested changes

2020-12-13 06:09 UTC, skeiya commented on ProjectsTM.UI.TaskList/ColDefinition.cs
> +                var te = GetText(listItems[0], sortCol, viewData);
動作確認用のコードは消しましょう。

2020-12-13 06:10 UTC, skeiya commented
> 外部仕様から
> エラーの行だけ今と逆向きにソートすればよいと考えて修正入れてしまったのですが、
> 確認で流れてきているデータを確認すると
> 
> ColDefinition.Sort内の下の処理で
> listItems = listItems.OrderByDescending(l => GetText(l, sortCol, viewData)).ToList();
> GetTextでもどってくる値(文字列)でソートしてるように思っていて確認すると常に"未完”が
> 返っているように見えたのですがこれはどういったデータ構造というかソートのロジックに
> なっているのでしょうか？

「C#　LINQ」というキーワードで調べてみてください。

2020-12-13 06:18 UTC, skeiya approved these changes

2020-12-13 06:19 UTC, merged