未プッシュのコミットがあることをステータスバーに表示するよう追加
skeiya/ProjectsTM pull request #297
Opened 2021-01-09 02:10 UTC by MatsukageRyo

2021-01-09 13:49 UTC, skeiya approved these changes
未コミットの編集があることも通知したいですね。

2021-01-11 06:46 UTC, MatsukageRyo commented
@skeiya 未コミットの編集があることを通知するよう追加しました。

2021-01-11 08:40 UTC, skeiya requested changes

2021-01-11 08:40 UTC, skeiya commented on ProjectsTM.Service/RemoteChangePollingService.cs
> +        private async Task TriggerUnpushedCommitCheck(string filePath)
UnpushedChangeくらいの名前のほうがよさそう。

2021-01-11 15:04 UTC, MatsukageRyo commented on ProjectsTM.Service/RemoteChangePollingService.cs
> +        private async Task TriggerUnpushedCommitCheck(string filePath)
ありがとうございます。修正しました。

2021-01-11 15:16 UTC, skeiya approved these changes

2021-01-11 15:16 UTC, merged