自分のタスクをパッと見れるようにする対応
skeiya/ProjectsTM pull request #298
Opened 2021-01-09 11:40 UTC by naotoAkashi42

ブランチ切り直しました。

■ ドロップダウンに_userNameでソートする選択肢を追加

■ TaskList.IsMatchPatternに条件を追加
　(所属)をつけるとIsMatchPatternにかからないので独自っぽい実装を入れてしまっていますが
　あまりよくないでしょうか？

![image](https://user-images.githubusercontent.com/71385466/104090509-97da6880-52ba-11eb-89ee-e4633182bb92.png)

↑で実験したのですが(所属)がついていると"()"が悪いのか、trueが返りませんでした。

2021-01-09 13:46 UTC, skeiya requested changes

2021-01-09 13:46 UTC, skeiya commented on ProjectsTM.UI.TaskList/TaskListForm.cs
> +            comboBoxPattern.Items.Add($"あなた({_userName})のタスク");
string.IsNullOrEmpty(_userName)の条件を付けましょう。
（_userNameを指定していないときの動作が奇妙に見えてしまうので。）

2021-01-09 13:46 UTC, skeiya commented on ProjectsTM.UI.TaskList/TaskListForm.cs
> +            gridControl1.Option = new TaskListOption(_userName, false, string.Empty);
こんな感じで正規表現を指定すればよいはず。
"^\[.*?\]\[.*?\]\[.*?" + _usernam" + ".*?\]\[.*?\]"

2021-01-09 14:34 UTC, naotoAkashi42 commented on ProjectsTM.UI.TaskList/TaskListForm.cs
> +            comboBoxPattern.Items.Add($"あなた({_userName})のタスク");
ありがとうございます！
個人設定がない場合の条件を追加しました。

2021-01-10 07:20 UTC, naotoAkashi42 commented on ProjectsTM.UI.TaskList/TaskListForm.cs
> +            gridControl1.Option = new TaskListOption(_userName, false, string.Empty);
すみません。いまいち正規表現がわからず調べているのですが、
現状のタスクリストの動きで質問なのですが、

![image](https://user-images.githubusercontent.com/71385466/104116805-4afc9d80-535f-11eb-92c3-93970ef172db.png)

↑だと更新ボタンからソートしてちゃんと対象のタスクが取れるのですが、

![image](https://user-images.githubusercontent.com/71385466/104116832-80a18680-535f-11eb-9efa-e6f820e63bcb.png)

↑だとソートでちゃんとタスクがとれないのは意図通りなのでしょうか？

2021-01-11 08:38 UTC, skeiya commented on ProjectsTM.UI.TaskList/TaskListForm.cs
> +            gridControl1.Option = new TaskListOption(_userName, false, string.Empty);
正規表現なので「0 100\(A\)」とすれば期待通りになるはずです。

2021-01-11 15:15 UTC, skeiya requested changes

2021-01-11 15:15 UTC, skeiya commented on ProjectsTM.UI.TaskList/TaskListForm.cs
> +        private static bool IsPersonalSettingNotSet(string userName)
メソッド名はなるべく否定形にしないほうが良い。
IsValidPersonalSettingのような肯定的な名前にして、呼び出す側で!を付けたほうが読みやすい。

2021-01-17 06:29 UTC, naotoAkashi42 commented on ProjectsTM.UI.TaskList/TaskListForm.cs
> +        private static bool IsPersonalSettingNotSet(string userName)
ありがとうございます！覚えておきます！

2021-01-17 06:30 UTC, naotoAkashi42 commented on ProjectsTM.UI.TaskList/TaskListForm.cs
> +            gridControl1.Option = new TaskListOption(_userName, false, string.Empty);
ありがとうございます！
調べた感じ
円マークつけないとうまくいっていなかったので、そのような修正を入れました。

2021-01-24 00:43 UTC, closed without merging