Users/matsukage/tool tip history
skeiya/ProjectsTM pull request #314
Opened 2021-02-07 13:42 UTC by MatsukageRyo

2021-02-07 14:06 UTC, skeiya requested changes

2021-02-07 14:06 UTC, skeiya commented on ProjectsTM.Model/WorkItem.cs
> +            var srcStr = Name +
担当者は比較しなくてよいのかな？

2021-02-07 14:16 UTC, skeiya commented
↓これを使って、XMLのロード時にどの行だったのかを取得して、WorkItemを行番号の対応関係を保持するのが良いかなぁ、と思っていました。
https://stackoverflow.com/questions/4471001/get-line-number-for-xelement-here

対応関係の保持はDictionary<WorkItem, pair<startLine, endLine>>みたいなイメージ。KEYの比較はWorkItemのequalsそのままでよさそう。

で、ツールチップ表示時に、対象行にgit blameするイメージ。
git blameの待ち時間が気になる場合は、非同期化&キャッシュする。

2021-02-07 15:29 UTC, MatsukageRyo commented on ProjectsTM.Model/WorkItem.cs
> +            var srcStr = Name +
ありがとうございます。漏れていました。
追加しました。

2021-02-07 15:30 UTC, MatsukageRyo commented on ProjectsTM.Service/GitRepositoryService.cs
> +        public static string ParseLastUpdateDateAndUserName(string str)
privateでよかったので修正しました。

2021-02-07 15:31 UTC, MatsukageRyo commented on ProjectsTM.Service/GitRepositoryService.cs
> +        public static string GetLastUpdateInfo(string filePath, int lineNo)
ありがとうございます、GetLastUpdateDateAndUserName()へ修正しました。

2021-02-07 15:34 UTC, MatsukageRyo commented on ProjectsTM.Model/WorkItem.cs
> +            var srcStr = Name +
ありがとうございます。漏れていました。追加しました。

2021-02-08 23:14 UTC, MatsukageRyo commented
@skeiya こんなイメージでしょうか？

・対応関係の保持はDictionary<WorkItem, pair<startLine, endLine>>
（XML情報の保持はやめる）

・KEYの比較はWorkItemのequals
（Md5ハッシュ値をXMLへ出力するのをやめる）

・ツールチップ表示時に、対象複数行に対してgit blameする

・git blameの結果から、複数の履歴結果をパースする。その中の最新日時のものをWorkItem最終更新情報として採用する

・XML読み書き時にDictionary<WorkItem, pair<startLine, endLine>>を更新する

2021-02-09 14:32 UTC, skeiya commented
はい。うまくいくかはわからないけど。
gitなし環境でも動作することを目指すなら違う設計を考えるけど、git前提とするならHashのような2次生成物を保持するのは不整合の元なので避けたほうが良いです。

2021-02-11 11:46 UTC, MatsukageRyo commented
@skeiya  上記の方針でいけました。ありがとうございます。

2021-02-13 02:59 UTC, skeiya requested changes

2021-02-13 02:59 UTC, skeiya commented on ProjectsTM.Service/WorkItemLastUpdateDateAndUserNameService.cs
> +    public class WorkItemLastUpdateDateAndUserNameService
class名が長いと思う。例えばEditorFindServiceとかでどうだろう。

2021-02-13 02:59 UTC, skeiya commented on ProjectsTM.Service/WorkItemLastUpdateDateAndUserNameService.cs
> +            var xmlWorkItems = GetXmlLines(XElement.Load(filePath, LoadOptions.SetLineInfo).Element(nameof(WorkItems)));
戻り値のxmlWorkItemsは使用していないように見える。使用していないなら、GetXmlLinesの命名が変なのかも。

2021-02-13 02:59 UTC, skeiya commented on ProjectsTM.Service/WorkItemLastUpdateDateAndUserNameService.cs
> +            foreach (var m in e.Elements("WorkItemsOfEachMember"))
WorkItems.csのFromXmlあたりのコードと重複部分があるけど、共通化できないかなぁ。

2021-02-13 02:59 UTC, skeiya commented on ProjectsTM.Service/ToolTipService.cs
> +                s.Append("最終更新："); s.AppendLine();
gitが使えない環境など、GetDateAndUserNameが空を返す時は、"最終更新："というのが表示されないようにしておきたい。

2021-02-13 02:59 UTC, skeiya commented on ProjectsTM.Service/ToolTipService.cs
>          private string GetDescrptionFromOtherWorkItem(WorkItem hoveringWorkItem)
知りたいのは、最後に編集した人がだれか？だけじゃないのかな？

2021-02-21 12:55 UTC, skeiya commented on ProjectsTM.Service/ToolTipService.cs
> +                s.Append("最終更新："); s.AppendLine();
gitがインストールされていません。と表示されるようにした。

2021-02-21 13:21 UTC, skeiya approved these changes

2021-02-23 05:06 UTC, merged