自分のタスクをパッと見れるようにする対応
skeiya/ProjectsTM pull request #317
Opened 2021-02-13 12:47 UTC by naotoAkashi42

■MainFormから_taskListManager.Showを呼ぶ際に個人設定(ユーザの名前)をセット
　・_taskListManagerにプロパティ追加
　・_taskListFormのコンストラクタの引数にstringを一つ追加。
■taskListForm内でuserNameが空文字(個人設定未設定)でない場合にComboBoxにuserNameの選択肢を追加するように修正。

2021-02-17 13:29 UTC, skeiya requested changes

2021-02-17 13:29 UTC, skeiya commented on ProjectsTM.UI.Main/MainForm.cs
> +            _taskListManager.UserName = _me == null ? string.Empty : _me.NaturalString;
UserNameはstring型ではなくMember型にしたほうが良い。

2021-02-17 13:29 UTC, skeiya commented on ProjectsTM.UI.TaskList/TaskListForm.cs
> +            if (comboBoxPattern.Text.Contains(_userName)) return GetSortPatternFormUserName(_userName);
このif分の分岐の意味合いがわからないです。

2021-02-17 13:29 UTC, skeiya commented on ProjectsTM.UI.TaskList/TaskListForm.cs
> +            if (comboBoxPattern.SelectedIndex != 0 || !IsUserSettingSet()) return;
このif分の分岐の意味合いがわからないです。

2021-02-17 13:29 UTC, skeiya commented on ProjectsTM.UI.TaskList/TaskListForm.cs
> +            if (userName.Contains("(")) userName = userName.Replace("(", @"\(");
Regex.Unescapeを使うと良さそう。

2021-02-17 13:29 UTC, skeiya commented on ProjectsTM.UI.TaskList/TaskListForm.cs
> +            if (comboBoxPattern.Text.Equals($"あなた({_userName})に割り当てられたタスク")) return;
$"あなた({_userName})に割り当てられたタスク"という文言がSetUserNameSortSelectと重複しています。

2021-02-21 01:57 UTC, naotoAkashi42 commented on ProjectsTM.UI.Main/MainForm.cs
> +            _taskListManager.UserName = _me == null ? string.Empty : _me.NaturalString;
string型(プリミティブ型)をやめ、Member型に修正しました。

2021-02-21 01:58 UTC, naotoAkashi42 commented on ProjectsTM.UI.TaskList/TaskListForm.cs
> +            if (comboBoxPattern.Text.Contains(_userName)) return GetSortPatternFormUserName(_userName);
関数に切り出して読みやすくしました。

2021-02-21 01:58 UTC, naotoAkashi42 commented on ProjectsTM.UI.TaskList/TaskListForm.cs
> +            if (comboBoxPattern.SelectedIndex != 0 || !IsUserSettingSet()) return;
関数に切り出して読みやすくしました。

2021-02-21 01:58 UTC, naotoAkashi42 commented on ProjectsTM.UI.TaskList/TaskListForm.cs
> +            if (userName.Contains("(")) userName = userName.Replace("(", @"\(");
Regex.Escapeを使うように修正しました。

2021-02-21 01:59 UTC, naotoAkashi42 commented on ProjectsTM.UI.TaskList/TaskListForm.cs
> +            if (comboBoxPattern.Text.Equals($"あなた({_userName})に割り当てられたタスク")) return;
重複した文言を変数で受けるように修正しました。

2021-02-21 06:24 UTC, skeiya requested changes

2021-02-21 06:24 UTC, skeiya commented on ProjectsTM.UI.Main/MainForm.cs
>              _taskListManager.Show();
_taskListManager.Show(_me);とするほうが単純でよい。（不要な自由度が少ない）

2021-02-21 06:24 UTC, skeiya commented on ProjectsTM.UI.Main/TaskListManager.cs
> +            var dispUserName = User == null ? string.Empty : User.NaturalString;
この時点ではまだ文字列化する必要はないと思うので、なるべくMemberクラスのまま扱ったほうが良い。

2021-02-23 04:29 UTC, naotoAkashi42 commented on ProjectsTM.UI.Main/MainForm.cs
>              _taskListManager.Show();
引数で渡すように変更しました。

2021-02-23 04:29 UTC, naotoAkashi42 commented on ProjectsTM.UI.Main/TaskListManager.cs
> +            var dispUserName = User == null ? string.Empty : User.NaturalString;
TaskListFormにわたるまではMemberで扱うように修正しました。

2021-02-23 05:17 UTC, skeiya requested changes

2021-02-23 05:17 UTC, skeiya commented on ProjectsTM.UI.Main/ManageMySettingForm.cs
> +            TaskListForm.ChangeMySetting?.Invoke(this, new MySettingChangeEventArgs(Selected));
モーダルダイアログでの変更内容の通知は、ダイアログ閉じた後にダイアログから内容を取り出して引き渡すほうが、つながりが明示的で簡単になるので良い。
イベントでの通知は、モードレスダイアログなど、処理間のつながりに自由度が必要な場合に用いる。

2021-02-23 05:55 UTC, naotoAkashi42 commented on ProjectsTM.UI.Main/ManageMySettingForm.cs
> +            TaskListForm.ChangeMySetting?.Invoke(this, new MySettingChangeEventArgs(Selected));
ありがとうございます。
イベントで通知するのをやめ
MyManageSettingFormを閉じる　→　編集後の個人設定を取得　→　TaskListFormの更新
という流れになるように修正しました。

2021-02-23 09:40 UTC, skeiya requested changes

2021-02-23 09:40 UTC, skeiya commented on ProjectsTM.UI.Common/MySettingChangeEventArgs.cs
> +    public class MySettingChangeEventArgs
不要になっているはず。

2021-02-23 11:05 UTC, naotoAkashi42 commented on ProjectsTM.UI.Common/MySettingChangeEventArgs.cs
> +    public class MySettingChangeEventArgs
ありがとうございます。
削除しました。

2021-02-23 14:55 UTC, skeiya requested changes

2021-02-23 14:55 UTC, skeiya commented on ProjectsTM.UI.Main/TaskListManager.cs
> +            if (taskListForms.Count == 0) return;
このif文は不要。Countがゼロの時はForEachが1度も実行されない、となるだけ。

2021-02-23 14:55 UTC, skeiya commented on ProjectsTM.UI.TaskList/TaskListForm.cs
> +            _userName = me == null ? string.Empty : me.NaturalString;
まだ、Memberのまま持ち続けられそう。

2021-02-26 14:05 UTC, naotoAkashi42 commented on ProjectsTM.UI.TaskList/TaskListForm.cs
> +            _userName = me == null ? string.Empty : me.NaturalString;
Member型のフィールドで保持し、必要な際にstring型に変換するように修正しました。

2021-02-28 08:12 UTC, skeiya approved these changes

2021-02-28 08:14 UTC, merged